---
jobs:
- name: job-unit-testing
  public: true
  serial: true
  plan:
  - get: resource-todo-app
    trigger: true
  - task: php-test-web-app
    config:
      params:
        GITHUB_TOKEN: {{github-token}}
    file: resource-todo-app/ci/task/run-test.yml



- name: deploy-to-pws
  public: true
  serial: true
  plan:
  - get: resource-todo-app
    trigger: true
    passed: [job-unit-testing]
  - put: deploy-to-pws
    params:
      manifest: resource-todo-app/manifest.yml
      path: resource-todo-app/
      environment_variables:
        COMPOSER_GITHUB_OAUTH_TOKEN: {{github-token}} 
      current_app_name: todo_apps_toshiomaki

resources:

- name: resource-todo-app
  type: git
  source:
    uri: https://github.com/toshiomakiyy/todo-apps-php-cf.git
    branch: feature/adding_concourse_pipeline


- name: deploy-to-pws
  type: cf
  source:
    api: https://api.system.pcf.shinji62.ovh
    username: {{pws-username}}
    password: {{pws-password}}
    organization: {{pws-org}}
    space: {{pws-space}}
    skip_cert_check: true
